apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vuejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: nuxt-test
        image: chluke/nuxt-test:latest
---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-service
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: vuejs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vuejs-ingress
  labels:
    traffic-type: external
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: vuejs.bpmcrowd.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vuejs-service
          servicePort: http
